print("HHHHH     HHHHH  EEEEEEEEEEE  LLLLLL          LLLLLL               OOOOO")
print("HHHHH     HHHHH  EEEE         LLLLLL          LLLLLL             OOO   OOO")
print("HHHHH     HHHHH  EEEE         LLLLLL          LLLLLL            OOO     OOO")
print("HHHHHHHHHHHHHHH  EEEEEEEEEEE  LLLLLL          LLLLLL           OOO       OOO")
print("HHHHHHHHHHHHHHH  EEEEEEEEEEE  LLLLLL          LLLLLL            OOO     OOO")
print("HHHHH     HHHHH  EEEE         LLLLLL          LLLLLL             OOO   OOO")
print("HHHHH     HHHHH  EEEE         LLLLLLLLLLLLLL  LLLLLLLLLLLLLL      OOO OOO")
print("HHHHH     HHHHH  EEEEEEEEEEE  LLLLLLLLLLLLLL  LLLLLLLLLLLLLL        OOO")